spring.application.name=Subscription-Tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/subtracker
spring.datasource.username=pigg
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME:}
spring.mail.password=${MAILTRAP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM:no-reply@subtracker.com}
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.timezone=${APP_TIMEZONE:Asia/Taipei}

# OAuth2 (Gmail)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/gmail.readonly
