spring.application.name=Subscription-Tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/subtracker
spring.datasource.username=pigg
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME:}
spring.mail.password=${MAILTRAP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
